// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PulseWatch.Data.Context;

#nullable disable

namespace PulseWatch.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PulseWatch.Core.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 459, DateTimeKind.Utc).AddTicks(9854),
                            Name = "Tech News"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 461, DateTimeKind.Utc).AddTicks(2389),
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 461, DateTimeKind.Utc).AddTicks(2397),
                            Name = "C# / .NET"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 461, DateTimeKind.Utc).AddTicks(2402),
                            Name = "JavaScript & Web"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 461, DateTimeKind.Utc).AddTicks(2407),
                            Name = "Cybersecurity"
                        });
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Feeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(5404),
                            IsActive = true,
                            Name = "Hacker News Frontpage",
                            URL = "https://hnrss.org/frontpage"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6646),
                            IsActive = true,
                            Name = "The Verge",
                            URL = "https://www.theverge.com/rss/index.xml"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6654),
                            IsActive = true,
                            Name = "MIT Technology Review",
                            URL = "https://www.technologyreview.com/topnews.rss"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6659),
                            IsActive = true,
                            Name = "Reddit Machine Learning",
                            URL = "https://www.reddit.com/r/MachineLearning/.rss"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6664),
                            IsActive = true,
                            Name = "Google AI Blog",
                            URL = "https://ai.googleblog.com/atom.xml"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6668),
                            IsActive = true,
                            Name = "OpenAI Blog",
                            URL = "https://openai.com/blog/rss.xml"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6673),
                            IsActive = true,
                            Name = "Microsoft .NET Blog",
                            URL = "https://devblogs.microsoft.com/dotnet/feed/"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6678),
                            IsActive = true,
                            Name = "ASP.NET Weblog",
                            URL = "https://weblog.asp.net/rss"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6683),
                            IsActive = true,
                            Name = "Bits and Pieces",
                            URL = "https://blog.bitsrc.io/feed"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6688),
                            IsActive = true,
                            Name = "Node.js Blog",
                            URL = "https://nodejs.org/en/feed/blog.xml"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6693),
                            IsActive = true,
                            Name = "React Blog",
                            URL = "https://reactjs.org/feed.xml"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6697),
                            IsActive = true,
                            Name = "Krebs on Security",
                            URL = "https://krebsonsecurity.com/feed/"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 1, 26, 13, 45, 31, 466, DateTimeKind.Utc).AddTicks(6702),
                            IsActive = true,
                            Name = "Dark Reading",
                            URL = "https://www.darkreading.com/rss.xml"
                        });
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Summary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrendId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrendId");

                    b.HasIndex("UserId");

                    b.ToTable("Summaries");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Trend", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Trends");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Category", b =>
                {
                    b.HasOne("PulseWatch.Core.Entities.User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Feed", b =>
                {
                    b.HasOne("PulseWatch.Core.Entities.Category", "Category")
                        .WithMany("Feeds")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PulseWatch.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Note", b =>
                {
                    b.HasOne("PulseWatch.Core.Entities.Category", "Category")
                        .WithMany("Notes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PulseWatch.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Summary", b =>
                {
                    b.HasOne("PulseWatch.Core.Entities.Trend", "Trend")
                        .WithMany("Summaries")
                        .HasForeignKey("TrendId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PulseWatch.Core.Entities.User", "User")
                        .WithMany("Summaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Trend");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Trend", b =>
                {
                    b.HasOne("PulseWatch.Core.Entities.Category", "Category")
                        .WithMany("Trends")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Category", b =>
                {
                    b.Navigation("Feeds");

                    b.Navigation("Notes");

                    b.Navigation("Trends");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.Trend", b =>
                {
                    b.Navigation("Summaries");
                });

            modelBuilder.Entity("PulseWatch.Core.Entities.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Summaries");
                });
#pragma warning restore 612, 618
        }
    }
}
